'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Graphics_Designer.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to drawarc &lt;x&gt; &lt;y&gt; &lt;width&gt; &lt;height&gt; &lt;startAngle&gt; &lt;sweepAngle&gt; &lt;lineWidth&gt; &lt;color&gt;
        '''drawbezier &lt;x0&gt; &lt;y0&gt; &lt;x1&gt; &lt;y1&gt; ... &lt;x3&gt; &lt;y3&gt; &lt;lineWidth&gt; &lt;color&gt;
        '''drawbeziers &lt;x0&gt; &lt;y0&gt; &lt;x1&gt; &lt;y1&gt; ... &lt;xN&gt; &lt;yN&gt; &lt;lineWidth&gt; &lt;color&gt;
        '''drawclosedcurve &lt;x0&gt; &lt;y0&gt; &lt;x1&gt; &lt;y1&gt; ... &lt;xN&gt; &lt;yN&gt; &lt;lineWidth&gt; &lt;color&gt;
        '''fillclosedcurve &lt;x0&gt; &lt;y0&gt; &lt;x1&gt; &lt;y1&gt; ... &lt;xN&gt; &lt;yN&gt; &lt;color&gt;
        '''drawcurve &lt;x0&gt; &lt;y0&gt; &lt;x1&gt; &lt;y1&gt; ... &lt;xN&gt; &lt;yN&gt; &lt;lineWidth&gt; &lt;color&gt;
        '''drawellipse &lt;x&gt; &lt;y&gt; &lt;width&gt; &lt;height&gt; &lt;lineWidth&gt; &lt;color&gt;
        '''fillellipse &lt;x&gt; &lt;y&gt; &lt;width&gt; &lt;height&gt; &lt;color&gt;
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property documentation() As String
            Get
                Return ResourceManager.GetString("documentation", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
